Feature/unit test
Star-Academy/Summer1400-SE-Team25 pull request #2
Opened 2021-08-02 11:17 UTC by Adibov

2021-08-03 12:03 UTC, mdyerf approved these changes
In my opinion perfectly fine !

2021-08-07 06:35 UTC, amirarab888 requested changes

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/controller/FileHandler.java
> +    private void extractWords(File file) {
چرا وید ریترن میکنه؟

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/controller/FileHandler.java
> +                fileMapper.addWordToInvertedIndex(file.getName(), readWord);
یه تابع بشه

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/controller/FileHandler.java
> +    public void initialize(String directoryName) {
الان وید ریترن میکنه این تابع رو سخت میشه تست کرد

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/model/DocumentFile.java
> +//            e.printStackTrace();
کد کامنت شده نداشته باشید

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/model/DocumentFile.java
> +            result.append(END_OF_FILE_PREVIEW);
تابع بشه

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/model/FileMapper.java
> +    public void addDocument(File file) {
چرا ویده

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/model/FileMapper.java
> +    public void addWordToInvertedIndex(String fileName, String word) {
چرا ویده؟

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/model/InvertedIndex.java
> +    public void addWord(DocumentFile documentFile, String word) {
چرا ویده؟

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/model/InvertedIndex.java
> +    public void addDocument(DocumentFile newDocument) {
چرا ویده؟

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/util/WordUtil.java
> +        var stemmer = new PorterStemmer();
چرا این جا 
new
شده؟

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/util/WordUtil.java
> +                stopWords.add(fileScanner.nextLine());
تابع

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/main/java/util/WordUtil.java
> +//            e.printStackTrace();
کد کامنت شده !!!!

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/test/java/MainTest.java
> +    public void testMainMethod() {
چرا خالیه؟

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/test/java/controllerTest/FIleHandlerTest.java
> +        fileHandler.initialize(INVALID_PATH);
این جا چون وید بوده نتونستید درست تستش کنید

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/test/java/controllerTest/FIleHandlerTest.java
> +        fileHandler.initialize(VALID_PATH);
این جا همین طور

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/test/java/controllerTest/QueryHandlerTest.java
> +    public void setUp() {
extract methods

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/test/java/modelTest/FileMapperTest.java
> +    public void testDocumentTwice() {
چی رو تست کردید این جا

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/test/java/modelTest/FileMapperTest.java
> +    public void testAddValidWord() {
چی رو تست کردید این جا؟

2021-08-07 06:35 UTC, amirarab888 commented on Phase3/src/test/java/view/UserViewTest.java
> +public class UserViewTest {
مقادیر ثابت در متغیر کانست

2021-08-07 10:30 UTC, FarshidNooshi requested changes

2021-08-07 10:30 UTC, FarshidNooshi commented on Phase3/src/main/java/Main.java
> +    final static String DEFAULT_PATH = "src/main/java/EnglishData";
access modifier

2021-08-07 10:30 UTC, FarshidNooshi commented on Phase3/src/test/java/controllerTest/FIleHandlerTest.java
> +        fileHandler.initialize(VALID_PATH);
اینجا چی تست شده ؟!

2021-08-07 10:30 UTC, FarshidNooshi commented on Phase3/src/test/java/controllerTest/QueryHandlerTest.java
> +        var searchResult1 = new HashSet<DocumentFile>() {
متد خیلی طولانیه 
بشکنیدش به چنتا متد

2021-08-07 10:30 UTC, FarshidNooshi commented on Phase3/src/test/java/modelTest/DocumentFileTest.java
> +        invalidDocument.previewDocument();
اینجا چی تست شده؟

2021-08-07 10:30 UTC, FarshidNooshi commented on Phase3/src/test/java/modelTest/DocumentFileTest.java
> +        Object object = new Object();
var

2021-08-07 10:30 UTC, FarshidNooshi commented on Phase3/src/test/java/modelTest/queryTest/OROperatorTest.java
> +        assertFalse(result.contains(additionalDocumentFile));
برای این متد و کلاسش و متد های مشابهش تو کلاسای دیگه این 
assertion ها
توی متد های جداگونه با اسم های مناسبشون باشن
مثلا:
testOneAddition_Expected_notContaintingAdditionalDocuments

2021-08-07 10:30 UTC, FarshidNooshi commented on Phase3/src/test/java/utilTest/WordUtilTest.java
> +        wordUtil = new WordUtil("src/main/java/StopWord");
اینجا چی تست شده؟

2021-08-07 13:20 UTC, Adibov commented on Phase3/src/main/java/model/DocumentFile.java
> +//            e.printStackTrace();
اینو به خاطر این گذاشتیم چون این تست رو داشتیم که توی اون کچ می‌رفت، بعد موقع ران کردن تستای اون استک‌تریس رو پرینت می‌کرد و یه خورده زشت بود. خودتون هم گفته بودید درستش اینه که لاگ بنویسیم، دیگه کامنت کردیم

2021-08-08 06:45 UTC, Adibov commented on Phase3/src/main/java/controller/FileHandler.java
> +    private void extractWords(File file) {
بالاخره اینم لیست ریترن کنه، یه متدی باید اونو بگیره و فور بزنه روشون و ادش کنه به اینورتد ایندکس که خب اون وید میشه

2021-08-08 06:55 UTC, Adibov commented on Phase3/src/main/java/model/InvertedIndex.java
> +    public void addWord(DocumentFile documentFile, String word) {
اینم خاصیت اینورتد ایندکسه. یعنی دو نوع کوئری داره، یکیش اضافه کردنه، یکیش هم گت کردنه. حالا واسه اد کردن هم که خب منطقی نیست چیزی برگردونیم.

2021-08-08 06:56 UTC, Adibov commented on Phase3/src/main/java/util/WordUtil.java
> +                stopWords.add(fileScanner.nextLine());
یه خطه :))

2021-08-08 06:56 UTC, Adibov commented on Phase3/src/main/java/util/WordUtil.java
> +//            e.printStackTrace();
اینم به خاطر همون مشکل قبلی کامنت کردیم

2021-08-15 06:44 UTC, merged