Phase4
Star-Academy/Summer1400-SE-Team25 pull request #3
Opened 2021-08-03 09:24 UTC by SamanEN

2021-08-03 12:02 UTC, mdyerf commented on Phase4/Students Grade and Average/Students Grade and Average/View.cs
> +        public void Run()
better to name Print or something more meaningful

2021-08-03 12:02 UTC, mdyerf commented on Phase4/Students Grade and Average/Students Grade and Average/View.cs
> +            studentsList.Sort((a, b) => a.GetGradesAverage().CompareTo(b.GetGradesAverage()) );
sorting is not the responsibility of this class

2021-08-03 12:02 UTC, mdyerf commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        public void Parse()
it's better for this methods to return list of students

2021-08-03 12:02 UTC, mdyerf commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        private void AssignGradesToStudents()
responsibility of parser class is to read and parse JSON files and not handling or manipulating data

2021-08-03 12:02 UTC, mdyerf commented on Phase4/Students Grade and Average/Students Grade and Average/Grade.cs
> +namespace Students_Grade_and_Average
naming convention: StudentsGradeAndAverage

2021-08-07 06:40 UTC, amirarab888 requested changes

2021-08-07 06:40 UTC, amirarab888 commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        }
چرا این حالت رو استفاده کردید؟؟

2021-08-07 06:40 UTC, amirarab888 commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +            var studentsFile = new StreamReader(studentsFilePath);
چرا این جا 
new 
شده؟

2021-08-07 06:40 UTC, amirarab888 commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +            var gradesFile = new StreamReader(gradesFilePath);
و این جا

2021-08-07 06:40 UTC, amirarab888 commented on Phase4/Students Grade and Average/Students Grade and Average/StudentsScoreHandler.cs
> +            foreach (var student in _students)
از 
linq
استفاده کنید

2021-08-07 06:40 UTC, amirarab888 commented on Phase4/Students Grade and Average/Students Grade and Average/StudentsScoreHandler.cs
> +            foreach (var student in _students)
تابع بشه داخل بلاک

2021-08-07 07:29 UTC, SamanEN commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        }
سینتکسش رو بهبود دادم اما دلیلش این هست که کار این کلاس ساخت نمرات و دانشجویان از روی فایل است و برای همین نیاز داریم داخل کلاس این فیلد ست بشه و از بیرون کلاس فقط دریافت شه.

2021-08-07 10:36 UTC, FarshidNooshi requested changes
فایل های جاوا ریموو بشن لطفا

2021-08-07 10:36 UTC, FarshidNooshi commented on Phase3/src/main/java/Main.java
> +public class Main {
بچه ها فایل های 
JAVA
توی این 
PR
رو حذف کنید همشونو

2021-08-07 10:36 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        public List<Student> Students { get; private set; }
readonly 
کنید اینارو که دیگه تغییرشون نمیدید

2021-08-07 10:36 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/StudentsScoreHandler.cs
> +        public List<Student> Students
اینو بنویسید :
public List<Student> Students { get; }

2021-08-07 10:36 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/StudentsScoreHandler.cs
> +        private List<Student> _students;
این رو حذف کنید

2021-08-13 05:03 UTC, amirarab888 commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        }
خب فقط گتر میذاشتید

2021-08-13 05:05 UTC, amirarab888 approved these changes

2021-08-14 15:32 UTC, FarshidNooshi approved these changes

2021-08-15 06:42 UTC, merged