Phase5
Star-Academy/Summer1400-SE-Team25 pull request #4
Opened 2021-08-07 07:56 UTC by SamanEN

2021-08-07 10:50 UTC, FarshidNooshi requested changes

2021-08-07 10:50 UTC, FarshidNooshi commented on .gitignore
>  # End of https://www.toptal.com/developers/gitignore/api/visualstudiocode,jetbrains+all,java,csharp
این کامنت ها بهتره نباشن

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase3/src/main/java/Main.java
> +public class Main {
فایل جاوا چرا توی این pr
هستش ؟

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        private List<Grade> _grades;
remove beshe

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        public List<Grade> Grades
auto she

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        public List<Student> Students
in ham auto beshe

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +    class Parser
dalili ke public nistesh class chie ?

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/Program.cs
> +            var parser = new Parser("Students.json", "Grades.json");
constant ha joda beshan az dakhele code

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase4/Students Grade and Average/Students Grade and Average/StudentsScoreHandler.cs
> +        public List<Student> Students
auto beshe

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase5/SearchEngine/SearchEngine/Model/Document.cs
> +        private const int DocumentPreviewCharacterCount = 27;
چرا readonly 
نیستن ؟

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase5/SearchEngine/SearchEngineTest/ModelTest/DocumentParserTest.cs
> +            // Assert.Throws<FileNotFoundException>(() =>
کد چرا کامنت شده ؟

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase5/SearchEngine/SearchEngineTest/ModelTest/DocumentTest.cs
> +            // Assert.Throws<FileNotFoundException>(InitializeInvalidDocument);
چرا کامنت شده کد؟

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase5/SearchEngine/SearchEngineTest/ModelTest/InvertedIndexTest.cs
> +        public void TestIndex()
فقط یدونه تست ؟!

2021-08-07 10:50 UTC, FarshidNooshi commented on Phase5/SearchEngine/SearchEngineTest/ModelTest/OperatorTest/OperatorTest.cs
> +            var actualResult = andOperator.Operate(_index, _currentSearchResultList);
متد طولانی شده با وجود تلاشتون برای کوتاه کردنش

2021-08-08 06:59 UTC, SamanEN commented on Phase3/src/main/java/Main.java
> +public class Main {
این برنچ از فاز ۴ گرفته شده و فاز ۴ هم از فاز ۳ برای همین فایلای فاز ۳ هم اینجا موندن

2021-08-08 07:00 UTC, SamanEN commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        private List<Grade> _grades;
فایل فاز ۴ هست و در
PR
خودش اصلاحش کردم.

2021-08-08 07:00 UTC, SamanEN commented on Phase4/Students Grade and Average/Students Grade and Average/Parser.cs
> +        public List<Grade> Grades
اینهم برای فاز ۴ است.

2021-08-15 06:38 UTC, merged